/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import bitcamp.menu.MenuGroup;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotEquals;

class AppTest {

  @Test
  @DisplayName("MenuGroup 은 만들때마다 서로 다른 주소를 갖는다.")
  void isSameInstance() {
    MenuGroup mainMenu = MenuGroup.getInstance("메인");
    MenuGroup mainMenu2 = MenuGroup.getInstance("메인1");

    assertNotEquals(mainMenu, mainMenu2);
  }
}
