/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  @DisplayName("MenuGroup 은 만들때마다 서로 다른 주소를 갖는다.")
  void isSameInstance() {
  }
}
